const actionType = {
  REQUEST_LOADING_SUFFIX : '_REQUEST_LOADING',
  REQUEST_FAIL_SUFFIX : '_REQUEST_FAIL',
  REQUEST_SUCCESS_SUFFIX : '_REQUEST_SUCCESS',

  POST : 'POST'
}

export default actionType