const actionType = {
  REQUEST_POSTS : 'REQUEST_POSTS',
  RECEIVE_POSTS : 'RECEIVE_POSTS',
  SELECT_SUBREDDIT : 'SELECT_SUBREDDIT',
  INVALIDATE_SUBREDDIT : 'INVALIDATE_SUBREDDIT'
}

// export const REQUEST_POSTS = 'REQUEST_POSTS'
// export const RECEIVE_POSTS = 'RECEIVE_POSTS'
// export const SELECT_SUBREDDIT = 'SELECT_SUBREDDIT'
// export const INVALIDATE_SUBREDDIT = 'INVALIDATE_SUBREDDIT'

export default actionType